trigger:
  branches:
    include:
    - '*'

schedules:
  - cron: "0 3 * * 0"
    displayName: Weekly Build
    branches:
      include:
      - main

variables:
  versionMajor: 1
  versionMinor: 0

stages:

- stage: build
  jobs:
  - job: build
    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
        command: 'restore'
        feedsToUse: 'config'
        nugetConfigPath: './src/nuget.config'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: "Pack FM.AzureTableExtensions.Library"
      inputs:
        command: pack
        packagesToPack: '$(Build.SourcesDirectory)/src/FM.AzureTableExtensions.Library/FM.AzureTableExtensions.Library.csproj'
        packDestination: '$(Build.ArtifactStagingDirectory)'
        buildProperties: 'Version="$(versionMajor).$(versionMinor).$(Build.BuildId)"'

    - task: DotNetCoreCLI@2
      displayName: "Pack FM.AzureTableLogger"
      inputs:
        command: pack
        packagesToPack: '$(Build.SourcesDirectory)/src/FM.AzureTableLogger/FM.AzureTableLogger.csproj'
        packDestination: '$(Build.ArtifactStagingDirectory)'
        buildProperties: 'Version="$(versionMajor).$(versionMinor).$(Build.BuildId)"'

    - publish: $(Build.artifactStagingDirectory)
      displayName: Publish NuGet artifact
      artifact: nuget

- stage: publish
  jobs:
    - job: publish
      pool:
        vmImage: 'windows-latest'

      steps:
      - download: current
        artifact: nuget

      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        displayName: 'NuGet push'
        inputs:
          command: push
          packagesToPush: '$(Pipeline.Workspace)/nuget/*.nupkg'
          publishVstsFeed: 'f6b61452-5280-47a1-b802-b2cfc8630b77/c57e8cd1-2aa2-4c0d-96cb-450405f73d4d'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))